package custwebrecords

import "github.com/lpuig/scopeleccustomerweb/recordset"

func NewCustomerWebRecords() *recordset.RecordSet {
	rs := recordset.NewRecordSet()
	rs.AddHeader(recordset.Record{
		"Identity.WorkOrderId",
		"Identity.CustomerReference",
		"Identity.ProjectCode",
		"Identity.Contract",
		"Identity.WorkOrderState",
		"Planning.PlannedDateOrdered",
		"Planning.DateRdv",
		"Planning.Marge",
		"Planning.ContractualDate",
		"Templating.Criteria1",
		"Templating.Criteria2",
		"Templating.Criteria3",
		"Templating.Criteria4",
		"Coordinates.StreetNumber",
		"Coordinates.NumberComplement",
		"Coordinates.StreetName",
		"Coordinates.AddressComplement",
		"Coordinates.PostalCode",
		"Coordinates.City",
		"Coordinates.Country",
		"Coordinates.Latitude",
		"Coordinates.Longitude",
		"Client.ClientFullName",
		"Client.TelMobile",
		"Client.TelFix",
		"Client.MarketType",
		"Client.GTI",
		"Client.GTR",
		"Connection.Node",
		"Connection.Information",
		"ParticularConditions.Criteria1",
		"ParticularConditions.Criteria2",
		"ParticularConditions.Criteria3",
		"ParticularConditions.Criteria4",
		"ParticularConditions.Criteria5",
		"ParticularConditions.Criteria6",
		"ParticularConditions.Criteria7",
		"ParticularConditions.Criteria8",
		"ParticularConditions.Criteria9",
		"ParticularConditions.Criteria10",
		"Routing.Criteria1",
		"Routing.Criteria2",
		"Routing.Criteria3",
		"Routing.Criteria4",
		"Dispatching.Criteria1",
		"Dispatching.Criteria2",
		"Dispatching.Criteria3",
		"Dispatching.Criteria4",
		"AdditionalInformation",
		"Comment",
		"Attachment.File1",
		"Attachment.Name1",
		"Attachment.File2",
		"Attachment.Name2",
		"Attachment.File3",
		"Attachment.Name3",
		"Extension.Key1",
		"Extension.Value1",
		"Extension.Key2",
		"Extension.Value2",
		"Extension.Key3",
		"Extension.Value3",
		"réponse SPRINT",
	})
	return rs
}
